Q1. What are the benefits of the built-in array package, if any?

Answer: The Array is much more rigid. That is, the items that an array contains must be of the same type. Therefore, the size of the item will also be the same. We can check the size of each item.

Q2. What are some of the array package's limitations?

Answer: An array which is formed will be homogeneous.

While declaring an array, passing size of an array is compulsory, and the size must be a constant.

Shifting is required for insertion or deletion of elements in an array

Q3. Describe the main differences between the array and numpy packages.

Answer: A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. A list is the Python equivalent of an array, but is resizeable and can contain elements of different types. The answer to above query the main difference in two is of performance.

Q4. Explain the distinctions between the empty, ones, and zeros functions.

Answer: The only difference between numpy.empty numpy.ones and numpy.zeros is that empty uses malloc and zeros uses calloc. Also zeros() and ones() are the NumPy library functions to create two different arrays. zeros() function is used to create an array based on the particular shape and type. All array elements are initialized to 0, which is created by the zeros() function. ones() function works like the zeros() function.

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

Answer: fromfunction() function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z). Parameters : function : [callable] The function is called with N parameters, where N is the rank of shape.

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

Answer:

In [5]:
pip install numpy


     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 186.2 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 260.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 269.5 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.5 MB 1.7 MB/s eta 0:00:10
    --------------------------------------- 0.3/16.5 MB 2.8 MB/s eta 0:00:06
   - -------------------------------------- 0.6/16.5 MB 4.1 MB/s eta 0:00:04
   -- ------------------------------------- 0.9/16.5 MB 4.5 MB/s eta 0:00:04
   -- ------------------------------------- 1.2/16.5 MB 4.9 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/16.5 MB 4.7 MB/s eta 0:00:04
  

In [6]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr + 1)

[2 3 4 5 6]


Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Answer: NO

In [7]:
#using scalar operations error came
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
a = arr += 1
print(a)

SyntaxError: invalid syntax (4216562642.py, line 5)

Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

Answer: NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. if longer strings is allocateed it might cause a computation problem basically increse the time complexity.

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

In [8]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = arr1+arr2
arr1 = arr1*arr2

print(arr)
print("\n",arr1)

[[ 6  8]
 [10 12]]

 [[ 5 12]
 [21 32]]


NumPy's concatenate function can be used to concatenate two arrays either row-wise or column-wise. Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0. The resulting array after row-wise concatenation is of the shape 6 x 3, i.e. 6 rows and 3 columns.

Q10. What is the best way to use a Boolean array to mask another array?

Answer: Boolean masking is typically the most efficient way to quantify a sub-collection in a collection. Masking in python and data science is when you want manipulated data in a collection based on some criteria. The criteria you use is typically of a true or false nature, hence the boolean part.

Using masked_where() function: Pass the two array in the function as a parameter then use numpy. ma. masked_where() function in which pass the condition for masking and array to be masked.

Using masked_where(), getmask() and masked_array() function: Pass the two array in the function as a parameter then use numpy. ma.

Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

Answer: one method is shown below standar then we can use pandas or using srpiting line by line to ding standard deviation. using pandas std() is generally nicer way and faster.

In [9]:
import math
def variance(data, ddof=0):
  n = len(data)
  mean = sum(data) / n
  return sum((x - mean) ** 2 for x in data) / (n - ddof)


def stdev(data):
  var = variance(data)
  std_dev = math.sqrt(var)
  return std_dev

stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])


2.4

In [10]:
# Q12. What is the dimensionality of a Boolean mask-generated array? 
# 
# Answer: it remain the same. Example below:

import numpy as np

arr = np.asarray([[[[1, 11], [2, 22], [3, 33]],
                   [[4, 44], [5, 55], [6, 66]]],
                  [[[7, 77], [8, 88], [9, 99]],
                   [[0, 32], [1, 33], [2, 34]]]])

masked_arr = np.ma.masked_less(arr, 3)

print(masked_arr)

[[[[-- 11]
   [-- 22]
   [3 33]]

  [[4 44]
   [5 55]
   [6 66]]]


 [[[7 77]
   [8 88]
   [9 99]]

  [[-- 32]
   [-- 33]
   [-- 34]]]]
